### ISSUE TITLE
Plugin description appears to have been copied from Otter Blocks

### ISSUE THREAD

**Issue by bobbingwide** [Codeinwp/blocks-css#17]
The `Description:` in `blocks-css.php` is the same as in https://github.com/Codeinwp/otter-blocks

Create beautiful and attracting posts, pages, and landing pages with Gutenberg Blocks and Template Library by Otter. Otter comes with dozens of Gutenberg blocks that are all you need to build beautiful pages.

**Comment by HardeepAsrani** [comment]
Hey @bobbingwide! Thanks for bringing it to our attention. Sorry for the delay, somehow GitHub doesn't notify me of this repository. :(

**Comment by HardeepAsrani** [comment]
Fixed in the latest version, thanks @bobbingwide!
