### ISSUE TITLE
extra classes removed from selector

### ISSUE THREAD

**Issue by michael-mass** [Codeinwp/blocks-css#51]
Specifically for the auto-generated class under the Advanced tab, in the Additional CSS Class(es) box, if that is used in the Custom CSS, it is replaced with "selector" when the tab is reopened.

For example, in this box is "ticss-73c7d56d." If I use that in the Custom CSS like so,
`selector:hover .ticss-73c7d56d {...`
when I close and reopen the tab, the `.ticss-73c7d56d` part is replaced with `selector` to read,
`selector:hover selector {...`

**Comment by HardeepAsrani** [comment]
Hey @michaelmass90 - sorry for not replying, we use a different GitHub to keep track of issues which is github.com/Codeinwp/gutenberg-css/ - now that I've seen it, I'll fix it right away. Sorry for not noticing sooner, it seems like a good find!
